server:
  port: 8081
  servlet:
    context-path: '/sisggar-api/'

spring:
  application:
    name: sisggar_api
  datasource:
    url:  jdbc:postgresql://localhost:5432/sisggardb?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  jackson:
    default-property-inclusion: non_null
  flyway:
    url: jdbc:postgresql://localhost:5432/sisggardb?createDatabaseIfNotExist=true&useSSL=false
    schemas: public
    user: postgres
    password: root

